[package]
name = "proompt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
copypasta-ext = { version = "0.4.4", default-features = false, features = [
    "wayland-bin",
    "x11-bin",
] }
ignore = "0.4"
